# Nanbu Linux —— packages 模块：执行 netinstall 选中的包（pacman 后端）
backend: pacman
skip_if_no_internet: false
update_db: true
update_system: false
pacman:
  num_retries: 1
  disable_download_timeout: false
  needed_only: true